---

apiVersion: v1
kind: pod
metadata:
  name: my-pod
  labels: 
    app: class-app
spec:
  containers:
    - name: class-container
      image: httpd
      ports:
        - containerPort: 80

    - name: tomcat-container
      image: tomcat
      ports:
        - containerPort: 8080

...

---

apiVersion: v1
kind: Service
metadata:
  name: class-service
spec:
  selector: 
    app: class-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

...


