---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-rs
  labels:
    app: cbz-app
spec:
  selector:
    matchLabels:
      app: cbz-app
      app: my-app
    # matchExpressions:
    #   - {key: app, operator: In, values: [my-app, cbz-app, demo-app]}
    #   - {key: env, operator: NotIn, values: [prod, dev]}
  template:
    metadata:
      labels:
        app: cbz-app
        env: test
        project: Cloudblitz
    spec:
      containers:
        - name: cbz-container
          image: httpd
          ports:
            - containerPort: 80
  replicas: 3
...

---

apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  selector: 
    app: cbz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

...